remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
title: "Portfolio"
description: "Welcome on my portfolio"

author:
  name: "Romain"
  bio: "FPGA engineer"
  avatar: "/assets/images/folio_picture.jpeg"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RomainPlmg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://fr.linkedin.com/in/romain-plumaugat-a131a21a2"
